(define (same-parity n . numbers)
  (define predicate (if (odd? n) odd? even?))
  (define (_same-parity numbers result)
    (cond ((null? numbers) result)
          ((predicate (car numbers)) (_same-parity (cdr numbers)
                                                   (cons (car numbers) result)))
          (else (_same-parity (cdr numbers)
                              result))))
  (reverse (_same-parity numbers (list n))))
