(define (cons x y)
  (lambda (m) (m x y)))
(define (car z)
  (z (lambda (p q) p)))
(define (cdr z)
  (z (lambda (p q) q)))

(let ((pair (cons 2 3)))
  (newline)
  (display "{")
  (display (car pair))
  (display ", ")
  (display (cdr pair))
  (display "}"))
