(define (square a)
  (* a a))
(define (largest a b c)
  (cond ((and (or (> a b) (> a c)) (< a b) (< a c)) a)
        ((and (or (> b a) (> b c)) (< b a) (< b c)) b)
        (else c)))
(define (middle a b c)
  (cond ((and (> a b) (> a c)) a)
        ((and (> b a) (> b c)) b)
        (else c)))
(define (sum-of-largest-squares a b c)
  (+ (square (middle a b c))
     (square (largest a b c))))
(sum-of-largest-squares 1 2 3)
(sum-of-largest-squares 6 4 5)