(define (square x) (* x x))
(define (cbrt-iter guess x)
  (if (good-enough? guess x)
      guess
      (cbrt-iter (improve guess x)
                 x)))
(define (improve guess x)
  (/ (+ (/ x (square guess))
        (* 2 guess))
     3)
  )
(define (good-enough? guess x)
  (< (/ (abs (- guess (improve guess x)))
        guess)
     0.0000000001))
(define (cube-root x)
  (cbrt-iter 1.0 x))

(cube-root 125)
(cube-root 1000000)